listener 1883
allow_anonymous true

persistence true
persistence_location C:/FogAndEdge/mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_type all
connection_messages true

connection awsiot
address ajfzkitfnbpep-ats.iot.us-east-1.amazonaws.com:8883

topic home/+/aggregates/+ out 1
topic home/+/alerts/+ out 1

bridge_protocol_version mqttv311
bridge_insecure false
cleansession true
clientid mosquitto-bridge-home1
start_type automatic
notifications false
try_private false
bridge_attempt_unsubscribe false
bridge_outgoing_retain false

bridge_cafile C:/FogAndEdge/certs/AmazonRootCA1.pem
bridge_certfile C:/FogAndEdge/certs/681bfabc3534e8c803c61dd80a4e59a30da009fde618eb8fa39b627a4959f6cd-certificate.pem.crt
bridge_keyfile C:/FogAndEdge/certs/681bfabc3534e8c803c61dd80a4e59a30da009fde618eb8fa39b627a4959f6cd-private.pem.key